version: '3.9'

services:
  strapi:
    image: alpeza/habmaps_strapi:latest
    container_name: habmaps_strapi
    ports:
      - "1337:1337"
    volumes:
      - strapi_data:/srv/app
    networks:
      - core_npm_hcinet

volumes:
  strapi_data:


networks:
  core_npm_hcinet:
    external: true
